---
title: 'Annual Statistical Report: Civil Commitment Procedures in Virginia'
author: "AA Allen, JK Bonnie"
date: "September, 2015"
output:
  pdf_document:
    toc: yes
  word_document: default
subtitle: University of Virginia Institute of Law, Psychiatry and Public Policy
---
```{r, echo=FALSE, warning=FALSE, message=FALSE}
source("CMS_prep.R")
CMS.Annual <- filter(CMS, !(FQtr == 1 & FYear==2009))
source("emagistrate_prep.R")
```


##ECOs
```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)
# 
# #emags <- read.csv("../data/ECOTDOFips08_14.txt")
# 
# #Path for running script outside of markdown
# #emags <- read.csv("data/ECOTDOFips08_14.txt")
# 
# # Create Fiscal Year Variable
# emags$FYear<- emags$Year
# emags[emags$Month > 6, ]$FYear <- as.numeric(emags[emags$Month > 6, ]$Year) + 1
# 
# #Create Fiscal Quarter Variable
# emags$FQtr <- emags$Month
# emags[emags$Month == 7|emags$Month==8| emags$Month==9, ]$FQtr <- 1
# emags[emags$Month == 10|emags$Month==11| emags$Month==12, ]$FQtr <- 2
# emags[emags$Month == 1|emags$Month==2| emags$Month==3, ]$FQtr <- 3
# emags[emags$Month == 4|emags$Month==5| emags$Month==6, ]$FQtr <- 4
# 
# # Create abbreviated month column, factored in accordance with fiscal calendar
# emags$FYMonthAbbrev <- factor(substr(month.name[emags$Month],1,3),levels=substr(c(month.name[7:12],month.name[1:6]),1,3))
# 
# # Create a uniq identifier for the month (may or may not be needed)
# emags$month_id <- factor(paste(emags$FYear, str_pad(as.character(emags$Month), 2, side="left", pad="0"), sep="-"))
# 
# #Force FIPs into the correct format
# emags$FIPS <- str_pad(as.character(emags$Fips.Code),3,side="left",pad="0")
```


```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
library(pander)
library(ggplot2)


emagsECOAnnual <- 
        emags %>%
        filter(Type=="ECO", FYear>2007) %>%
        group_by(FYear) %>%
        summarise(count = sum(Process.Count)) 

names(emagsECOAnnual)[names(emagsECOAnnual)=="FYear"] <- "Fiscal Year"
names(emagsECOAnnual)[names(emagsECOAnnual)=="count"] <- "# ECOs"

pander(emagsECOAnnual, caption = "Annual Frequency of ECOs Issued for Adults, FY08-FY15")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
ECO <- 
  emags %>%
  filter(Type=="ECO", FYear>2007)

ECOyearly <- 
  group_by(ECO, FYear) %>%
  summarise(count = sum(Process.Count))

p <-  ggplot(ECOyearly, aes(x=FYear, y=count)) + geom_line() + geom_point() + geom_text(size=3, aes(label=count, hjust=0.5, vjust=2)) + ylab("Number of ECOs") +  xlab("Fiscal Year")

p + ylim(0,max(ECOyearly$count)) + geom_line(size=1.2) + geom_point(size=3.5)+ ggtitle("Annual Frequency of ECOs Issued for Adults, FY08-FY15") + theme(plot.title = element_text(size=12))
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
source("ECO_Qtrly_Long_FY08-FY15_PLOT.R")

ECO_Qtrly_Long_Plot + ylim(1000,max(ECO_Qtrly_Long$count)) + geom_line(size=1.2) + ggtitle("Quarterly ECO Trends (Adults Only), FY08-FY15") + scale_x_discrete(labels=c("08-1", "08-2", "08-3", "08-4", "09-1", "09-2", "09-3", "09-4", "10-1", "10-2", "10-3", "10-4", "11-1", "11-2", "11-3", "11-4", "12-1", "12-2", "12-3", "12-4", "13-1", "13-2", "13-3", "13-4", "14-1", "14-2", "14-3", "14-4", "15-1", "15-2","15-3", "15-4")) + theme(axis.text.x = element_text(angle=90)) + theme(plot.title = element_text(size=12))

```


```{r, echo=FALSE, warning=FALSE, message=FALSE}

emagsECOMonthly <- 
        emags %>%
        filter(Type=="ECO", FYear>2007) %>%
        group_by(FYear, FYMonthAbbrev) %>%
        summarise(count = sum(Process.Count)) %>%
        spread(FYear, count)

names(emagsECOMonthly)[names(emagsECOMonthly)=="FYMonthAbbr"] <- "Month"


pander(emagsECOMonthly, caption = "Monthly Frequency of ECOs Issued for Adults, FY08-FY15", split.table = Inf)
```


```{r, echo=FALSE, warning=FALSE, message=FALSE}
ECO <- 
  emags %>%
  filter(Type=="ECO", FYear>2007)

ECO$Month <- str_pad(as.character(ECO$Month), 2, side="left", pad="0")

ECO$month_id <- factor(paste(ECO$FYear, as.character(ECO$Month), sep=" "))

ECOmonthly2 <- 
  group_by(ECO, month_id, FYear, FYMonthAbbrev) %>%
  summarise(count = sum(Process.Count))

#ECOmonthly2$monthGraph <- factor(ECOmonthly2$Month, levels=c("07", "08", "09", "10", "11", "12", "01", "02", "03", "04", "05", "06"))


p <- 
  ggplot(ECOmonthly2, aes(factor(FYMonthAbbrev), count, group=factor(FYear), color=factor(FYear))) + 
  geom_line() +
  ylab("Number of ECOs") +
  xlab("Month")

p + ylim(200,max(ECOmonthly2$count)) + geom_line(size=1.2) + ggtitle("Monthly Frequency of ECOs Issued for Adults, FY08-FY15") + geom_point(aes(shape=factor(FYear)), size=3) + scale_colour_discrete(name  ="Fiscal Year") + scale_shape_discrete(name="Fiscal Year") + theme(plot.title = element_text(size=12))
```




##TDOs

```{r, echo=FALSE, warning=FALSE, message=FALSE}
#emags <- read.csv("../data/ECOTDOFips08_14.txt")
library(dplyr)
library(stringr)
library(tidyr)
library(pander)
library(ggplot2)

# emags$FYear<- emags$Year
# emags[emags$Month > 6, ]$FYear <- as.numeric(emags[emags$Month > 6, ]$Year) + 1

emagsTDOAnnual <- 
        emags %>%
        filter(Type=="TDO", FYear>2007) %>%
        group_by(FYear) %>%
        summarise(count = sum(Process.Count)) 

names(emagsTDOAnnual)[names(emagsTDOAnnual)=="FYear"] <- "Fiscal Year"
names(emagsTDOAnnual)[names(emagsTDOAnnual)=="count"] <- "# ECOs"

pander(emagsTDOAnnual, caption = "Annual Frequency of TDOs Issued for Adults, FY08-FY15")

```


```{r, echo=FALSE, warning=FALSE, message=FALSE}
TDO <- 
  emags %>%
  filter(Type=="TDO", FYear>2007)

TDO$Month <- str_pad(as.character(TDO$Month), 2, side="left", pad="0")


TDO$month_id <- factor(paste(TDO$FYear, as.character(TDO$Month), sep=" "))

TDOyearly <- 
  group_by(TDO, FYear) %>%
  summarise(count = sum(Process.Count))

p <-  ggplot(TDOyearly, aes(x=FYear, y=count)) + geom_line() + geom_point() + geom_text(size=3, aes(label=count, hjust=0.5, vjust=2.5)) + ylab("Number of TDOs") +  xlab("Fiscal Year")

p + ylim(1250,max(TDOyearly$count)) + geom_line(size=1.2) + geom_point(size=3.5)+ ggtitle("Annual Frequency of TDOs Issued for Adults, FY10-FY15") + theme(plot.title = element_text(size=12))


```


```{r, echo=FALSE, warning=FALSE, message=FALSE}
source("TDO_Qtrly_Long_FY08-FY15_PLOT.R")

TDO_Qtrly_Long_Plot + ylim(3000,max(TDO_Qtrly_Long$count)) + geom_line(size=1.2) + ggtitle("Quarterly TDO Trends (Adults Only), FY08-FY15") + scale_x_discrete(labels=c("08-1", "08-2", "08-3", "08-4", "09-1", "09-2", "09-3", "09-4", "10-1", "10-2", "10-3", "10-4", "11-1", "11-2", "11-3", "11-4", "12-1", "12-2", "12-3", "12-4", "13-1", "13-2", "13-3", "13-4", "14-1", "14-2", "14-3", "14-4", "15-1", "15-2","15-3", "15-4")) + theme(axis.text.x = element_text(angle=90)) + theme(plot.title = element_text(size=12))

```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
#emags <- read.csv("../data/ECOTDOFips08_14.txt")
source("emagistrate_prep.R")
library(dplyr)
library(stringr)
library(tidyr)
library(pander)
library(ggplot2)

#emags$FYear<- emags$Year
#emags[emags$Month > 6, ]$FYear <- as.numeric(emags[emags$Month > 6, ]$Year) + 1

emags2 <- 
        emags %>%
        filter(Type=="TDO", FYear>2007) %>%
        group_by(FYear, FYMonthAbbrev) %>%
        summarise(count = sum(Process.Count)) %>%
        spread(FYear, count)

names(emags2)[names(emags2)=="FYMonthAbbr"] <- "Month"


pander(emags2, caption = "Monthly Frequency of TDOs Issued for Adults, FY08-FY15", split.table = Inf)

```


```{r, echo=FALSE, warning=FALSE, message=FALSE}

# emags$FYear<- emags$Year
# emags[emags$Month > 6, ]$FYear <- as.numeric(emags[emags$Month > 6, ]$Year) + 1

TDO <- 
  emags %>%
  filter(Type=="TDO", FYear>2007)

TDO$Month <- str_pad(as.character(TDO$Month), 2, side="left", pad="0")


TDO$month_id <- factor(paste(TDO$FYear, as.character(TDO$Month), sep=" "))

TDOmonthly2 <- 
  group_by(TDO, month_id, FYear, Month) %>%
  summarise(count = sum(Process.Count))

TDOmonthly2$monthGraph <- factor(TDOmonthly2$Month, levels=c("07", "08", "09", "10", "11", "12", "01", "02", "03", "04", "05", "06"))

p <- 
  ggplot(TDOmonthly2, aes(factor(monthGraph), count, group=factor(FYear), color=factor(FYear))) + 
  geom_line() +
  ylab("Number of TDOs") +
  xlab("Month")

p + ylim(1200,max(TDOmonthly2$count)) + geom_line(size=1.2) +
  ggtitle("Monthly Frequency of TDOs Issued for Adults, FY08-FY15") +  geom_point(aes(shape=factor(FYear)), size=3) + scale_colour_discrete(name  ="Fiscal Year") + scale_shape_discrete(name="Fiscal Year") + theme(plot.title = element_text(size=12))
```

##Initial Commitment Hearings
```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)
library(lubridate)
library(dplyr)

source("CMS_prep.R")
#CMS <- read.csv("../data/CMS_8_26.txt")
#FIPS_Codes <- read.csv("../data/FIPS_R.csv")

#Paths for running script outside of markdown
#CMS <- read.csv("data/CMS_8_26.txt")
#FIPS_Codes <- read.csv("data/FIPS_R.csv")

#remove extraneous columns
#CMS<- select(CMS, -ErrorType, -Notes, -CorrectionDate, -Received, -FilingDate, -ID)

# Strip Whitespace from some values
#CMS$HEAR.RSLT <- str_trim(CMS$HEAR.RSLT)
#CMS$CASE.TYP <- str_trim(CMS$CASE.TYP)
#CMS$MOT <- str_trim(CMS$MOT)

#Create Month, Year
#CMS$HEAR.DATE <- as.Date(CMS$HEAR.DATE, format = '%m/%d/%Y')
#CMS$Year<- year(CMS$HEAR.DATE)
#CMS$Month <- month(CMS$HEAR.DATE)

#Filter for no errors (keep or no?)
#CMS<- filter(CMS, Error< 1|is.na(Error))

# Create Fiscal Year Variable
#CMS$FYear<- CMS$Year
#CMS[CMS$Month > 6, ]$FYear <- as.numeric(CMS[CMS$Month > 6, ]$Year) + 1

#Create Fiscal Quarter Variable
#CMS$FQtr <- CMS$Month
#CMS[CMS$Month == 7|CMS$Month==8| CMS$Month==9, ]$FQtr <- 1
#CMS[CMS$Month == 10|CMS$Month==11| CMS$Month==12, ]$FQtr <- 2
#CMS[CMS$Month == 1|CMS$Month==2| CMS$Month==3, ]$FQtr <- 3
#CMS[CMS$Month == 4|CMS$Month==5| CMS$Month==6, ]$FQtr <- 4

# Create abbreviated month column, factored in accordance with fiscal calendar
#CMS$FYMonthAbbrev <- factor(substr(month.name[CMS$Month],1,3),levels=substr(c(month.name[7:12],month.name[1:6]),1,3))

# Create a uniq identifier for the month (may or may not be needed)
#CMS$month_id <- factor(paste(CMS$FYear, str_pad(as.character(CMS$Month), 2, side="left", pad="0"), sep="-"))

#Create FIPs column
#CMS$FIPS <- substr(CMS$CASE.NUMBER, 1, 4)

#Include FIPS names
#CMS <- merge(CMS, FIPS_Codes, by = c("FIPS"), all.x = TRUE)
#CMS <- CMS[,!names(CMS) %in% c("SHORT_FIPS","COURT")]
#names(CMS)[names(CMS)=="NAME"] <- "Locality"

#Use Pay Code to determine if Hearing is Initial
#CMS$Initial <- ifelse (CMS$PAY.CD == 41 | CMS$PAY.CD == 46, FALSE, TRUE)
#CMS$Initial [is.na(CMS$PAY.CD)] <- TRUE

# The first quarter of FY2009 (July, August, September) is incomplete, so it is removed from the dataset

#CMS.Annual <- filter(CMS, !(FQtr == 1 & FYear==2009))
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}

CMS_MonthlyHearingsInitial <- 
  CMS %>%
  filter(CASE.TYP=="MC", Initial=="TRUE") %>%
  group_by(Initial, FYMonthAbbrev, FYear) %>%
  summarise(count = n()) %>%
  spread(FYear, count) %>%
  select(-Initial)

names(CMS_MonthlyHearingsInitial)[names(CMS_MonthlyHearingsInitial)=="FYMonthAbbrev"] <- "Month"

pander(CMS_MonthlyHearingsInitial, caption  = "Monthly Frequency of Initial Commitment Hearings for Adults, FY09-FY15", split.table = Inf)
```


```{r, echo=FALSE, warning=FALSE, message=FALSE}

# load all necessary packages
library(dplyr)
library(tidyr)
library(pander)
library(ggthemes)

CMS_MonthlyHearingsInitialPlot <- 
   CMS %>%
  filter(CASE.TYP=="MC", Initial=="TRUE") %>%
  group_by(FYMonthAbbrev, FYear) %>%
  summarise(count = n())

MCInitialplot <- 
  ggplot(CMS_MonthlyHearingsInitialPlot, aes(factor(FYMonthAbbrev), count,  group=factor(FYear), color=factor(FYear))) + 
  geom_line() +
  ylab("Number of Commitment Hearings") +
  xlab("Month")

MCInitialplot + ylim(1200, max(CMS_MonthlyHearingsInitialPlot$count)) + geom_line(size=1.2) + geom_point(aes(shape=factor(FYear)), size=3) + scale_colour_discrete(name  ="Fiscal Year") + scale_shape_discrete(name="Fiscal Year") + 
  ggtitle("Monthly Frequency of Initial Commitment Hearings Involving Adults, FY09-FY15") + theme(plot.title = element_text(size=12))
```

##Recommitment Hearings
```{r, echo=FALSE, warning=FALSE, message=FALSE}
source("CMS_MC_RecommitmentHearings_Annual_FY09-F15_TABLE.R")

pander(CMS_Annual_Recommitment_Hearings, caption  = "Annual Frequency of Recommitment Hearings for Adults, FY10-FY15", split.table = Inf)

```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
source("CMS_MC_RecommitmentHearings_Annual_FY09-F15.R")

CMS_Annual_Recommitments_Plot + ylim(0,3000) + geom_line(size=1.2) + geom_point(size=3.5)+ ggtitle("Annual Frequency of Involuntary Commitment Orders for Adults, FY10-FY15") + theme(plot.title = element_text(size=12))


```


```{r, echo=FALSE, warning=FALSE, message=FALSE}

CMS_MonthlyHearingsRecommit <- 
  CMS %>%
  filter(CASE.TYP=="MC", Initial=="FALSE") %>%
  group_by(Initial, FYMonthAbbrev, FYear) %>%
  summarise(count = n()) %>%
  spread(FYear, count) %>%
  select(-Initial)

names(CMS_MonthlyHearingsRecommit)[names(CMS_MonthlyHearingsRecommit)=="FYMonthAbbrev"] <- "Month"

pander(CMS_MonthlyHearingsRecommit, caption  = "Monthly Frequency of Recommitment Hearings for Adults, FY09-FY15", split.table = Inf)
```


```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
library(pander)
library(ggthemes)

CMS_MonthlyHearingsRecommitPlot <- 
   CMS %>%
  filter(CASE.TYP=="MC", Initial=="FALSE") %>%
  group_by(Initial, FYMonthAbbrev, FYear) %>%
  summarise(count = n())

MCRecommitplot <- 
  ggplot(CMS_MonthlyHearingsRecommitPlot, aes(factor(FYMonthAbbrev), count, group=factor(FYear), color=factor(FYear))) + 
  geom_line() +
  ylab("Number of Recommitment Hearings") +
  xlab("Month")

MCRecommitplot + ylim(0, max(CMS_MonthlyHearingsRecommitPlot$count)) + geom_line(size=1.2) + geom_point(aes(shape=factor(FYear)), size=3) + scale_colour_discrete(name  ="Fiscal Year") + scale_shape_discrete(name="Fiscal Year") + 
  ggtitle("Monthly Frequency of Recommitment Hearings Involving Adults, FY09-FY15") + theme(plot.title = element_text(size=12))
```

##Involuntary Commitment Orders

```{r, echo=FALSE, warning=FALSE, message=FALSE}
source("CMS_MC_I_Annual_FY09-FY15_TABLE.R")
pander(CMS_AnnualCommitmentsInitial, caption  = "Annual Frequency of Commitment Orders for Adults (Initial Only), FY10-FY15", split.table = Inf)

```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
source("CMS_MC_I_Annual_FY09-FY15_PLOT.R")

CMS_Annual_Commitments_Plot + ylim(10000,15000) + geom_line(size=1.2) + geom_point(size=3.5)+ ggtitle("Annual Frequency of Involuntary Commitments Orders, FY10-FY15") + theme(plot.title = element_text(size=12))

```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
source ("CMS_MC_I_Monthly_FY09-FY15_TABLE.R")
pander(CMS_MonthlyCommitmentsInitial, caption  = "Monthly Frequency of Commitment Orders for Adults (Initial Only), FY09-FY15", split.table = Inf)

```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
source("CMS_MC_I_Monthly_FY09-FY15_PLOT.R")
MC_Iplot + ylim(600, max(CMS_MonthlyCommitmentsPlot$count)) + geom_line(size=1.2) + geom_point(aes(shape=factor(FYear)), size=3) + scale_colour_discrete(name  ="Fiscal Year") + scale_shape_discrete(name="Fiscal Year") + 
  ggtitle("Monthly Frequency of Involuntary Commitment Orders for Adults (Initial Only), FY09-FY15") + theme(plot.title = element_text(size=10))

```

##Mandatory Outpatient Treatment
```{r, echo=FALSE, warning=FALSE, message=FALSE}
source("CMS_MOT_Annual_Tot_FY09-FY15_Plot.R")
MOT_Annual_Plot + ylim(0,350) + geom_line(size=1.2) + geom_point(size=3.5)+ ggtitle("Annual Frequency of MOT Orders (All Types), FY09-FY15") + theme(plot.title = element_text(size=12))

```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
source("CMS_MOT_Qtrly_Tot_FY09-FY15_PLOT.R")
MOT_Qtrly_Tot_Plot + ylim(0,100) + geom_line(size=1.2) + geom_point(size=3.5)+ ggtitle("Quarterly MOT Trends (All Types), FY09-FY15") + scale_x_discrete(labels=c("09-2", "09-3", "09-4", "10-1", "10-2", "10-3", "10-4", "11-1", "11-2", "11-3", "11-4","12-1", "12-2", "12-3", "12-4", "13-1", "13-2", "13-3", "13-4", "14-1", "14-2", "14-3", "14-4", "15-1", "15-2","15-3", "15-4")) + theme(axis.text.x = element_text(angle=90)) + theme(plot.title = element_text(size=12))

```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
source("CMS_MOT_Annual_FY09_FY15_Table.R")

pander(CMS_MOT_Annual, caption= "Fiscal Year MOT Counts by Type", keep.line.breaks =TRUE,split.table = Inf)

```


```{r, echo=FALSE, warning=FALSE, message=FALSE}
source("CMS_MOT_Type_Qtrly_FY09-FY15_PLOT.R")
MOT_Type_Qtrly_Plot + ylim(0,85) + geom_line(size=1.2) + geom_point(aes(shape=factor(MOT_TYPE)), size=3) + scale_colour_discrete(name  ="MOT Type") + scale_shape_discrete(name="MOT Type") + ggtitle("Quarterly MOT Trends by Type, FY09-FY15") +
  scale_x_discrete(labels=c("09-2", "09-3", "09-4", "10-1", "10-2", "10-3", "10-4", "11-1", "11-2", "11-3", "11-4",
                            "12-1", "12-2", "12-3", "12-4", "13-1", "13-2", "13-3", "13-4",
                            "14-1", "14-2", "14-3", "14-4", "15-1", "15-2","15-3", "15-4")) + theme(axis.text.x = element_text(angle=90)) + theme(plot.title = element_text(size=12))


```
\newpage

```{r, echo=FALSE, warning=FALSE, message=FALSE}

source("CMS_Locality_MOT_FY15.R")
pander(CMS_MOT_FY15, caption= "MOT Types by Locality, FY15", keep.line.breaks=TRUE, split.table = Inf)
```

\newpage

```{r, echo=FALSE, warning=FALSE, message=FALSE}

library(stringr)
library(lubridate)
library(pander)
library(dplyr)
library(tidyr)

source("CMS_Locality_MOT.R")
pander(CMS_MOT, caption= "MOT Types by Locality, FY09-FY15", keep.line.breaks = TRUE,split.table = Inf)

# 
# #CMS <- read.csv("../data/CMS_8_26.txt")
# #FIPS_Codes <- read.csv("../data/FIPS_R.csv")
# 
# # Remove Extraneous columns from CMS table
# #CMS <- CMS[,!names(CMS) %in% c("Notes","Received","ErrorType","FilingDate","CorrectionDate")]
# 
# #Remove extra white space from around some values
# #CMS$HEAR.RSLT <- str_trim(CMS$HEAR.RSLT)
# #CMS$CASE.TYP <- str_trim(CMS$CASE.TYP)
# #CMS$MOT <- str_trim(CMS$MOT)
# 
# #Create Month and Year columns
# #CMS$HEAR.DATE <- as.Date(CMS$HEAR.DATE, format = '%m/%d/%Y')
# #CMS$Year<- year(CMS$HEAR.DATE)
# #CMS$Month <- month(CMS$HEAR.DATE)
# 
# #Filter for no errors (keep or no?)
# #CMS<- filter(CMS, Error< 1|is.na(Error))
# 
# # Create Fiscal Year Variable
# #CMS$FYear<- CMS$Year
# #CMS[CMS$Month > 6, ]$FYear <- as.numeric(CMS[CMS$Month > 6, ]$Year) + 1
# 
# #Create Fiscal Quarter Variable
# #CMS$FQtr <- CMS$Month
# #CMS[CMS$Month == 7|CMS$Month==8| CMS$Month==9, ]$FQtr <- 1
# #CMS[CMS$Month == 10|CMS$Month==11| CMS$Month==12, ]$FQtr <- 2
# #CMS[CMS$Month == 1|CMS$Month==2| CMS$Month==3, ]$FQtr <- 3
# #CMS[CMS$Month == 4|CMS$Month==5| CMS$Month==6, ]$FQtr <- 4
# 
# # Create abbreviated month column, factored in accordance with fiscal calendar
# #CMS$FYMonthAbbrev <- factor(substr(month.name[CMS$Month],1,3),levels=substr(c(month.name[7:12],month.name[1:6]),1,3))
# 
# # Create a uniq identifier for the month (may or may not be needed)
# #CMS$month_id <- factor(paste(CMS$FYear, str_pad(as.character(CMS$Month), 2, side="left", pad="0"), sep="-"))
# 
# #Create FIPs column
# #CMS$FIPS <- substr(CMS$CASE.NUMBER, 1, 4)
# 
# #Include FIPS names
# #CMS <- merge(CMS, FIPS_Codes, by = c("FIPS"), all.x = TRUE)
# #CMS <- CMS[,!names(CMS) %in% c("SHORT_FIPS","COURT")]
# #names(CMS)[names(CMS)=="NAME"] <- "Locality"
# 
# #Use Pay Code to determine if Initial
# #CMS$Initial <- ifelse (CMS$PAY.CD == 41 | CMS$PAY.CD == 46, FALSE, TRUE)
# #CMS$Initial [is.na(CMS$PAY.CD)] <- TRUE
# 
# ########### HERE'S THE MEAT #########
# # Create table of the counts of 4 Different MOT Types for all localities
# CMS_MOT <- filter(CMS, CASE.TYP =="MC", HEAR.RSLT %in% c("MO", "I"))%>%
#   mutate(MOT_TYPE)
#   group_by(Locality,HEAR.RSLT, MOT, Initial)%>%
#   filter((HEAR.RSLT == "I" & (MOT == "Y") ) | HEAR.RSLT == "MO" ) %>%
#   summarise(count = n()) %>%
#   spread(Locality,count)
# 
# CMS_MOT$MOT_TYPE <- "X"
# CMS_MOT[CMS_MOT$HEAR.RSLT=="I" & CMS_MOT$MOT=="Y" & !CMS_MOT$Initial ,]$MOT_TYPE <- "TYPE1"
# CMS_MOT[CMS_MOT$HEAR.RSLT=="I" & CMS_MOT$MOT=="Y" & CMS_MOT$Initial ,]$MOT_TYPE <- "TYPE2"
# CMS_MOT[CMS_MOT$HEAR.RSLT=="MO"  & !CMS_MOT$Initial ,]$MOT_TYPE <- "TYPE3"
# CMS_MOT[CMS_MOT$HEAR.RSLT=="MO"  & CMS_MOT$Initial ,]$MOT_TYPE <- "TYPE4"
# #CMS_MOT <- as.data.frame(CMS_MOT)
# CMS_MOT <- select(CMS_MOT,-Initial,- MOT,- HEAR.RSLT)
# CMS_MOT <- t(CMS_MOT)
# 
# 
# # Trying to give MOT type column names
# #CMS_MOT <- as.data.frame(CMS_MOT,colnames)
# #colnames(CMS_MOT) <- CMS_MOT[49,]
# 
# CMS_MOT <- as.data.frame(CMS_MOT)
# 
# CMS_MOT<- rename(CMS_MOT, Stepdown_Recommitment_Discharge=V1, Stepdown_Initial_Discharge=V2, Stepdown_New_Hearing=V3, Direct=V4)
# CMS_MOT <- CMS_MOT[-50,]
# pander(CMS_MOT, caption= "MOT Types by Locality")
```


##Alternative Transportation Orders

```{r, echo=FALSE, warning=FALSE, message=FALSE}
ATO <- read.csv("../data/ATO with TimeInfo_8_26_15.txt")

ATO<-filter(ATO, Form=="ECO"| Form=="TDO")

  ATO_Tot<- ATO %>%
  group_by(FYEAR, Form) %>%
  summarise(count = n()) %>%
  spread(FYEAR, count)

  ATO_Tot[is.na(ATO_Tot)]<- 0
  
names(ATO_Tot)[names(ATO_Tot)=="Form"] <- "Type"
names(ATO_Tot)[names(ATO_Tot)=="ATO.Category"] <- "Provider"
names(ATO_Tot)[names(ATO_Tot)=="2010"] <- "FY10"
names(ATO_Tot)[names(ATO_Tot)=="2011"] <- "FY11"
names(ATO_Tot)[names(ATO_Tot)=="2012"] <- "FY12"
names(ATO_Tot)[names(ATO_Tot)=="2013"] <- "FY13"
names(ATO_Tot)[names(ATO_Tot)=="2014"] <- "FY14"
names(ATO_Tot)[names(ATO_Tot)=="2015"] <- "FY15"
pander(ATO_Tot, caption = "Annual Frequency of ATOs Issued for Adults, by Order Type, FY10-FY15")

```

```{r, echo=FALSE, warning=FALSE, message=FALSE}

source("ATO_Qtrly_Long_FY10-FY15_PLOT.R")
ATO_Annual_Plot + ylim(0,60) + geom_line(size=1.2) + ggtitle("Quarterly ATO Trends (Adults Only), FY10-FY15") + scale_x_discrete(labels=c("10-1", "10-2", "10-3", "10-4", "11-1", "11-2", "11-3", "11-4", "12-1", "12-2", "12-3", "12-4", "13-1", "13-2", "13-3", "13-4", "14-1", "14-2", "14-3", "14-4", "15-1", "15-2","15-3", "15-4")) + theme(axis.text.x = element_text(angle=90)) + theme(plot.title = element_text(size=12))
```

\newpage

```{r, echo=FALSE, warning=FALSE, message=FALSE}

ATO_Provider<- ATO %>%
  group_by(FYEAR, ATO.Category) %>%
  summarise(count = n()) %>%
  spread(FYEAR, count)

names(ATO_Provider)[names(ATO_Provider)=="ATO.Category"] <- "Transportation Provider"
names(ATO_Provider)[names(ATO_Provider)=="2010"] <- "FY10"
names(ATO_Provider)[names(ATO_Provider)=="2011"] <- "FY11"
names(ATO_Provider)[names(ATO_Provider)=="2012"] <- "FY12"
names(ATO_Provider)[names(ATO_Provider)=="2013"] <- "FY13"
names(ATO_Provider)[names(ATO_Provider)=="2014"] <- "FY14"
names(ATO_Provider)[names(ATO_Provider)=="2015"] <- "FY15"

ATO_Provider[is.na(ATO_Provider)]<- 0

pander(ATO_Provider, caption = "Annual Frequency of ATOs Issued for Adults, by Transportation Provider, FY10-FY15", split.cells=7)


```
